### ISSUE TITLE
画面遷移を作ってみました

### ISSUE THREAD

**Issue by a1935af** [Mamitsubute/irochilog#1]
[画面遷移ver1.xlsx](https://github.com/Mamitsubute/irochilog/files/3386068/ver1.xlsx)

**Comment by a1935af** [comment]
[画面遷移ver1.xlsx](https://github.com/Mamitsubute/irochilog/files/3386088/ver1.xlsx)
差し替えです

**Comment by a1935af** [comment]
[画面遷移ver1.xlsx](https://github.com/Mamitsubute/irochilog/files/3386102/ver1.xlsx)

差し替えです

**Comment by youknowcast** [comment]
ありがとうございます．遅くなってすいません．いくつかコメントです．
* ログイン画面には，Twitter連携による新規アカウント登録リンクも必要だと思います
* そういえば，ログアウトのこと考えられてませんでしたね・・どうするか次回検討しましょう
* Twitter 起動 はどちらかというと，チェックつけたときに遷移，という話だったような気もしますが，こちらもどうするかは次回，，
* 「ポケモン個別」画面の メモ ってなんでしょう？

**Comment by a1935af** [comment]
返事遅くなってすみません。
3連休で仕事でシステム切替してまして、明日も返せないかもしれません。

・ログイン画面にTwitter連携による新規アカウント登録リンクを追加しました。
・twitterはご指摘の通りチェックしたら何か出て、不要ならスワイプするような話だったのを思い出しました。チェックしたら遷移するように変更しました。
[画面遷移ver1.1.xlsx](https://github.com/Mamitsubute/irochilog/files/3389972/ver1.1.xlsx)

・ポケモン個別画面のメモは、確かポケモンをゲットした場所を記録しても良いのでは？という話があったので入れてみました。なくても良いかもしれません。

・ログアウトは次回・・

**Comment by a1935af** [comment]
共通認識がとれたということで、一旦クローズします。
