### ISSUE TITLE
DB 設計

### ISSUE THREAD

**Issue by youknowcast** [Mamitsubute/irochilog#11]
migration ファイルできるところまで

**Comment by youknowcast** [comment]
migration file 作って，master data 系が入るとこまではざっくりと見ました．
今回はユーザの手入力はあまりないので validation は後回しでもよいのかなぁとか．

**Comment by youknowcast** [comment]
ふつうのやつ，イロチ をそれぞれ捕まえたかどうかのフラグと，捕まえた場所(これはイロチ用だけでよさそう)を管理するカラムが posession_monsters に必要かなぁとおもっています ．

すなわち，以下のような感じ．
- normal:bool
- irochi:bool
- get_place:string
- get_date:date

また，ユーザ名，sort_key の状態を保持しておきたいので， UserConfig テーブルを新設するかどうか考え中．(users は devise に使わせているので，こっちからの適当なカラム追加は事故のもとかなと)
この場合のカラムはいまのところ，以下のような感じかなぁと思っています．
- user_name:string
- sort_key: integer

**Comment by mamepika** [comment]
イロチだけに絞った想定でした。
通常も管理するのであれば、
shiny_possession_monstersと
possession_monstersの2つの似たようなテーブルで管理でしょうか。フラグでもよいですが…

**Comment by mamepika** [comment]
ソートなどの画面状態は、テーブル作って管理した方が良さそうですね。ただ、マストでは無いかなと思います。

**Comment by youknowcast** [comment]
なるほど、どっち(テーブル分割かフラグか)で考えてたんだろうなーと思ってました。
私は今回の場合はあまりテーブル分割にメリットを感じなかったのでフラグで提案した次第です。

まずは一覧画面実装してからですかねー

**Comment by mamepika** [comment]
未所持・所持の判定はフラグではなく、対象のポケモンの所持のレコードの有無で判定したいと思ってました。
メリットは余計なカラムが減ることでしょうか。
まずは一覧画面などですね。

**Comment by youknowcast** [comment]
そっちのほうがよさげですね＞レコードの有無
では shiny_possession_monsters 追加して、画面側には normal: true/false, shiny: true/false で返すようにします(v-vind するにもそっちのほうが都合がよいであろう、きっと・・)

**Comment by mamepika** [comment]
![irochi table](https://user-images.githubusercontent.com/7695409/62364562-c815c780-b55c-11e9-936f-3c3233e52fe5.PNG)
