### ISSUE TITLE
ログイン機能の実装

### ISSUE THREAD

**Issue by mamepika** [Mamitsubute/irochilog#24]

**Comment by youknowcast** [comment]
ガワは実装しました．
テストをちゃんとやったとは言い難いですが，ぼんやりとは動くようです．
見た目が壊滅的なのでどなたか面倒みていただければと．

**Comment by a1935af** [comment]
ログインだけ直しました。他もパスワード忘れたときの画面等があるようで、
必要そうだったら直しておきます。

**Comment by a1935af** [comment]
ただ、プルリクエストにも書いたのですが、usersフォルダの下のViewファイルをいくら直しても、まったく反映されませんでした。
なので、rails generate devise:views して deviseフォルダの下に作成して修正したところ、
変更が反映されたのでそのままdeviseフォルダの下を修正しました。
このやり方だと問題あるでしょうか？

**Comment by mamepika** [comment]
Vuetifyを使ってみようと思います。
ログイン画面は作ります。

ログイン機能については認証はTwitterに丸投げするので、PW忘れなどの考慮は不要です。

**Comment by a1935af** [comment]
良く分かっていなくて申し訳ないのですが、
結果、ルーティングもrailsのものは使用しないという事ですか？

**Comment by mamepika** [comment]
画面のルーティングはVue-routerですね。

**Comment by a1935af** [comment]
#34で対応するのでcloseします。
