### ISSUE TITLE
ログイン画面の実装

### ISSUE THREAD

**Issue by mamepika** [Mamitsubute/irochilog#34]
# Twitter連携によるログインを行える画面
トップページであるログイン画面を作成する

## ログイン機能
ログインはTwitter連携を行い、認証はTwitterで行うものとする。
ログイン画面には「Twitterアカウントでログイン」ボタンを設置する

## ログイン後の遷移
ログイン完了後は
ポケモンの一覧・所持状況を参照することができるダッシュボード画面に遷移する。
ダッシュボードはSPAで作成する。

**Comment by a1935af** [comment]
ボタンは、他のラベルなどの文字が英語だったので一旦、「sign in with twitter」にしました。

**Comment by mamepika** [comment]
あれ、やろうと思ってたんですが

**Comment by a1935af** [comment]
作業がコンフリクトしましたね・・・

**Comment by a1935af** [comment]
今日の計画で、ログインはSPAにはせず、静的なページとする話となったので、
継続して作業します。テキストボックスは廃止し、Twitterボタンだけにします。

**Comment by a1935af** [comment]
Twitterボタンは安部さんに作成してもらいました。背景は一旦公園の画像にしました。
完了と思われるのでクローズします。
