### ISSUE TITLE
ロゴがほしいです

### ISSUE THREAD

**Issue by youknowcast** [Mamitsubute/irochilog#5]
そういえば，ロゴどうしましょうね．

以下のジェネレータで適当につくったやつに「GO」の O 部分を付け足したイメージを作ってみました．幅とか解像度とか透過とか一切調整してないのであくまでサンプルです．
https://fontmeme.com/ja/font-pokemon-go-logo/
PokemonGO font では日本語の提供はないようだったので，全部ローマ字です．

![d15ef11c720db95284459d57d7a199f4](https://user-images.githubusercontent.com/2378303/61201578-e9cf1c00-a71f-11e9-81c8-41471bc6dbae.png)

**Comment by mamepika** [comment]
これいいですね！！

**Comment by Mamitsubute** [comment]
素敵です〜！！！

**Comment by a1935af** [comment]
公式を見てみると母音が小文字だったので、試しにやってみましたが(モンスターボールは除く)、
安部さんのものが良いですね。　rとhを大文字にすると、くどくなりました。

安部さんベース、頭文字と母音を小文字、母音を小文字
![image](https://user-images.githubusercontent.com/49624948/61376637-80e0d300-a8dc-11e9-8c3e-942ca1d2d5c3.png)

**Comment by youknowcast** [comment]
O の形の整形とか，r と c の横，もうちょっっとだけ文字間詰めたい，とかどなたかがんばりませんか(他力)

**Comment by mamepika** [comment]
![Irochi Log logo](https://user-images.githubusercontent.com/7695409/61575122-cda5f300-ab02-11e9-82fe-bb23313004ae.png)

**Comment by mamepika** [comment]
時間かけるのも勿体無いのでとりあえずこれで！

**Comment by youknowcast** [comment]
public/irochi_log.png として配置しました．
完了でよろしいのではないかと．
