### ISSUE TITLE
vue.js の組み込みをしてほしいです

### ISSUE THREAD

**Issue by youknowcast** [Mamitsubute/irochilog#9]
必要とおもわれる 作業は以下
* webpack 導入手順
* webpack の rails project への追加(static 配下へのデリバリ含む)
* SPA の大枠部分

**Comment by a1935af** [comment]
図書館でvue.jsの本を見てみましたが、今日知ったことは　SPA = シングルページアプリケーションでした。webpackは、vue.jsとは別の技術のようですね。
今のところ分かったのは、複数ファイルを１つにしてくれることでした。

**Comment by youknowcast** [comment]
私も vue.js に関しては，あまりきちんといじったことがないのですが，
公式の Guide を読むのが一番手頃なのかなぁという気がしています．
https://jp.vuejs.org/v2/guide/

**Comment by youknowcast** [comment]
手順については #14 でまとめます．

**Comment by youknowcast** [comment]
#18 で Webpacker, Vue, Vuetify を導入しました．
のちほど pr しますが，これらの動かし方についてもまとめました(yarn いれて yarn するだけですが・・)．
ログインまわりと Vue 使った SPA の食い合わせがあまりよろしくない気がしているのでもうちょっと考えます・・

**Comment by youknowcast** [comment]
とりあえずまぁええやろ，の精神．
(ちゃんと組み込めて動いてます)
